### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by tupui** [tupui/soroban-versioning#46]
From the previous milestone.
On mobile from the main page the modal cannot be closed as too large. And for the modals I would like that if we click outside of the modal it closes, not just by clicking on the x.

For this milestone. I am thinking about the following:

- [ ] 1. Removing the view project info from the project page and just show all info on the page (need to do a figma design first so we agree on the design).

- [ ] 2. Then add some logic to check that the hash of the toml file is the same as the onchain hash (and an alert or banner if not). 

- [ ] 3. Also a similar alert if the latest hash onchain cannot be found in GitHub. This is actually the goal of the project, help people see if the history changed or not.

- [x] 4. Pagination for the history view.

- [ ] 5. When going from main page to project endpoint, the wallet is not connected anymore. If a user connect, it should stay connected throughout the whole navigation, clicking on any button, going back and forth from any pages.

- [x] 6. Add some links to the doc for tansu file (when no config found and also in tooltip somewhere).

**Comment by 0xExp-po** [comment]
could you please explain more detail about the 6 item?

**Comment by tupui** [comment]
Item 6, basically every time we have a message saying tansu.toml, it should be a link to https://tansu.dev/docs/developers/project_information_file

**Comment by tupui** [comment]
Linking here the new design proposal you sent https://www.figma.com/design/qU4NsMBj1Q5YYpVoPI7DRU
