### ISSUE TITLE
Endpoint for projects for sharing

### ISSUE THREAD

**Issue by tupui** [tupui/soroban-versioning#54]
We should have an endpoint like `https://testnet.tansu.dev/project/tansu` so that people can share their projects directly.

This will also save quite some requests.

**Comment by 0xExp-po** [comment]
I'll resolve this issue

**Comment by tupui** [comment]
Putting this for visibility. Ideally we would like this to be working on the client. Once we have a backend we can reconsider. Though I would hope this could be on the client side as it's really a simple logic in JS to have.
