### ISSUE TITLE
Error handling from contract in dApp

### ISSUE THREAD

**Issue by tupui** [tupui/soroban-versioning#55]
The contract defines enum errors

```rust
enum Errors {
  UnexpectedError = 0,
  InvalidKey = 1,
  ProjectAlreadyExist = 2,
  UnregisteredMaintainer = 3,
  NoHashFound = 4,
  InvalidDomainError = 5,
  MaintainerNotDomainOwner = 6
}
```

In some cases it could be better to use this information to do proper error handling (log, flow, etc.)

**Comment by 0xExp-po** [comment]
I've done this and commit in this PR
https://github.com/tupui/soroban-versioning/pull/104
