### ISSUE TITLE
Store proposals on IPFS

### ISSUE THREAD

**Issue by tupui** [tupui/soroban-versioning#90]
Relates to https://github.com/tupui/soroban-versioning/issues/83#issuecomment-2475093808

Send the proposal to IPFS with Storacha to the DID of the project (https://docs.storacha.network/how-to/upload/). The proposal is a markdown file and can have images.

Here is an example of proposal

https://bafybeidsfg2rfmpgtisfnmk6lur5dmy6j4kwjblh2rhme6nrsvjcaci4jq.ipfs.w3s.link

To store the possible actions in XDR form. I think the best would be to store a json file (I will make an example tomorrow and provide another IPFS link.) This JSON file need to be loaded and displayed at the bottom of the proposal.

```json
{
	"approved": {
		"description": "What happens if this proposal is approved",
		"xdr": "AAAAAgAAAABiu...="
	},
	"rejected": {
		"description": "What happens if this proposal is rejected",
		"xdr": "AAAAAgAAAABiu...="
	},
	"cancelled": {
		"description": "What happens if this proposal is cancelled",
		"xdr": "AAAAAgAAAABiu...="
	}
}
```

The XDR field is optional.

See the [laboratory](https://lab.stellar.org/xdr/view?$=network$id=mainnet&label=Mainnet&horizonUrl=https:////horizon.stellar.org&rpcUrl=&passphrase=Public%20Global%20Stellar%20Network%20/;%20September%202015;&xdr$blob=AAAAAgAAAABiux7OLuqVSQDUmUyHmIaiVG5GFB906JiHnjzurXZuxACbP8IDPR2wAAAFlQAAAAEAAAAAAAAAAAAAAABnNUf5AAAAAAAAAAEAAAAAAAAAGAAAAAAAAAAB1//5EvQrxHWArEJHy9KH03yEtRE0DIeoyrbPMHLurCgQAAAAEd29yawAAAAMAAAASAAAAAAAAAABiux7OLuqVSQDUmUyHmIaiVG5GFB906JiHnjzurXZuxAAAAA0AAAAgAAAAANGgf0lmr7UMt9p+iHUnEjwW9PBkekHlVXUf+dYAAAAJAAAAAAAAAAAAAAABmvn//pgAAAAAAAAABAAAAAAAAAAEAAAAH40Nv9RSvSiFEc+w8vLfwUzANT1qGwyBMEt6xAtOlMpEAAAADAAAABgAAAAHX//kS9CvEdYCsQkfL0ofTfIS1ETQMh6jKts8wcu6sKBAAAABAAAAABAAAAAgAAAA8AAAAFQmxvY2sAAAAAAAADAAACqQAAAAAAAAAGAAAAAdf+RL0K8R1gKxCR8vSh9N8hLURNAyHqMq2zzBy7qwoEAAAAEAAAAAEAAAADAAAADwAAAARQYWlsAAAAEgAAAAAAAAAAYrsezi7qlUkA1JlMh5iGolRuRhQfdOiYh5487q12bsQAAAADAAACqQAAAAAAAAAGAAAAAdf+RL0K8R1gKxCR8vSh9N8hLURNAyHqMq2zzBy7qwoEAAAAFAAAAAEANnhdAAA+EAAAA0QAAAAAAAKpQgAAAAGtdm7EAAAAQFWk2Zx5WyWrDlNnXhDUqvfBf0ijuds1D1PNdVl+5kjy7sdAJ1KYZKREvw4uzO35IbUewNSMuyPKiB+tKOEF9Qk=;;) for some XDR example. We are storing in the JSON files the XDR as a string. But in the UI we are only interested in displaying the JSON form. The XDR should be a collapsible and scrollable as it can be long.

**Comment by 0xExp-po** [comment]
Hey, @tupui
in the IPFS, is the proposal description file name `proposal.md` whenever?

**Comment by 0xExp-po** [comment]
also, the action JSON data, is it stored as another file in IPFS?
then what is the file name?

**Comment by tupui** [comment]
Yes the proposal should always be `proposal.md`. When a user will create a proposal, it should create this file and send it to IPFS.

For the JSON data, I will make a new link with everything to show.

Let's call the file, `outcomes.json`

**Comment by tupui** [comment]
We only display the decoded data. So json. We do t need to show the XDR itself there.

What we will need is to add a link somewhere on the page to see the files on IPFS. This way people can verify for themselves everything if they want to.

**Comment by tupui** [comment]
Here is the new link with outcomes:

https://bafybeigstnjnededvbckmvlmodpw2m745i5lidmyttb4u7o6ouiudokbx4.ipfs.w3s.link

**Comment by 0xExp-po** [comment]
then I'll add 'link' icon to the beside of the titles 'Proposal Description' and 'Proposal Outcome'
the links will be like these for example with the above ipfs link

https://bafybeigstnjnededvbckmvlmodpw2m745i5lidmyttb4u7o6ouiudokbx4.ipfs.w3s.link/proposal.md
https://bafybeigstnjnededvbckmvlmodpw2m745i5lidmyttb4u7o6ouiudokbx4.ipfs.w3s.link/outcomes.json

**Comment by 0xExp-po** [comment]
like this
![image](https://github.com/user-attachments/assets/408bb400-baab-4517-8872-402dcf11345e)

and this
![image](https://github.com/user-attachments/assets/255766d5-117a-4aad-a0ea-df6e422c8edb)

**Comment by tupui** [comment]
That works 👍
